import { IPlan } from './plan/models/plan';

export let plans: IPlan[] = [
  {
    id: 1,
    name: 'A',
    lastTime: '01.01.2018',
    exercises: [
      {
        id: 1,
        muscleGroup: 'Breast',
        name: 'Push Up',
        sets: 3,
        repeat: 20,
        image: 'push-up.png',
        done: false,
      },
      {
        id: 2,
        muscleGroup: 'Leg',
        name: 'Squat',
        sets: 3,
        repeat: 20,
        image: 'squat.png',
        done: false,
      },
      {
        id: 3,
        muscleGroup: 'Abdominal',
        name: 'Sit Up',
        sets: 3,
        repeat: 20,
        image: 'sit-up.png',
        done: false,
      },
    ],
  },
  {
    id: 2,
    name: 'B',
    lastTime: '03.01.2018',
    exercises: [
      {
        id: 1,
        muscleGroup: 'Breast',
        name: 'Push Up',
        sets: 3,
        repeat: 20,
        image: 'push-up.png',
        done: false,
      },
      {
        id: 2,
        muscleGroup: 'Leg',
        name: 'Squat',
        sets: 3,
        repeat: 20,
        image: 'squat.png',
        done: false,
      },
      {
        id: 3,
        muscleGroup: 'Abdominal',
        name: 'Sit Up',
        sets: 3,
        repeat: 20,
        image: 'sit-up.png',
        done: false,
      },
    ],
  },
  {
    id: 3,
    name: 'C',
    lastTime: '05.01.2018',
    exercises: [
      {
        id: 1,
        muscleGroup: 'Breast',
        name: 'Push Up',
        sets: 3,
        repeat: 20,
        image: 'push-up.png',
        done: false,
      },
      {
        id: 2,
        muscleGroup: 'Leg',
        name: 'Squat',
        sets: 3,
        repeat: 20,
        image: 'squat.png',
        done: false,
      },
      {
        id: 3,
        muscleGroup: 'Abdominal',
        name: 'Sit Up',
        sets: 3,
        repeat: 20,
        image: 'sit-up.png',
        done: false,
      },
    ],
  },
];
